// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rocksdb_service.proto
// Protobuf C++ Version: 5.27.2

#include "rocksdb_service.pb.h"

#include <algorithm>
#include <type_traits>

#include "google/protobuf/descriptor.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/wire_format_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rocksdb {

inline constexpr PutResponse::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : success_{false}, _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PutResponse::PutResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PutResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PutResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PutResponseDefaultTypeInternal() {}
  union {
    PutResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PutResponseDefaultTypeInternal
        _PutResponse_default_instance_;

inline constexpr PutRequest::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : key_(&::google::protobuf::internal::fixed_address_empty_string,
           ::_pbi::ConstantInitialized()),
      value_(&::google::protobuf::internal::fixed_address_empty_string,
             ::_pbi::ConstantInitialized()),
      _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PutRequest::PutRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PutRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PutRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PutRequestDefaultTypeInternal() {}
  union {
    PutRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PutRequestDefaultTypeInternal
        _PutRequest_default_instance_;
}  // namespace rocksdb
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_rocksdb_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_rocksdb_5fservice_2eproto = nullptr;
const ::uint32_t TableStruct_rocksdb_5fservice_2eproto::offsets
    [] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::rocksdb::PutRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rocksdb::PutRequest, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::rocksdb::PutRequest, _impl_.value_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::rocksdb::PutResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rocksdb::PutResponse, _impl_.success_),
};

static const ::_pbi::MigrationSchema schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    {0, -1, -1, sizeof(::rocksdb::PutRequest)},
    {10, -1, -1, sizeof(::rocksdb::PutResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::rocksdb::_PutRequest_default_instance_._instance,
    &::rocksdb::_PutResponse_default_instance_._instance,
};
const char descriptor_table_protodef_rocksdb_5fservice_2eproto
    [] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        "\n\025rocksdb_service.proto\022\007rocksdb\"(\n\nPutR"
        "equest\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 "
        "\001(\t\"\036\n\013Pu"
        "tResponse\022\017\n\007success\030\001 \001(\0102B\n\016RocksDBSer"
        "vice\0220\n\003Put\022\023.rocksdb.PutRequest\032\024.rocks"
        "db.PutResponseb\006proto3"};
static ::absl::once_flag descriptor_table_rocksdb_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable
    descriptor_table_rocksdb_5fservice_2eproto = {
        false,
        false,
        182,
        descriptor_table_protodef_rocksdb_5fservice_2eproto,
        "rocksdb_service.proto",
        &descriptor_table_rocksdb_5fservice_2eproto_once,
        nullptr,
        0,
        2,
        schemas,
        file_default_instances,
        TableStruct_rocksdb_5fservice_2eproto::offsets,
        file_level_enum_descriptors_rocksdb_5fservice_2eproto,
        file_level_service_descriptors_rocksdb_5fservice_2eproto,
};
namespace rocksdb {
// ===================================================================

class PutRequest::_Internal {
 public:
};

PutRequest::PutRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rocksdb.PutRequest)
}
inline PROTOBUF_NDEBUG_INLINE PutRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena, const Impl_& from,
    const ::rocksdb::PutRequest& from_msg)
    : key_(arena, from.key_), value_(arena, from.value_), _cached_size_{0} {}

PutRequest::PutRequest(::google::protobuf::Arena* arena, const PutRequest& from)
    : ::google::protobuf::Message(arena) {
  PutRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rocksdb.PutRequest)
}
inline PROTOBUF_NDEBUG_INLINE PutRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
    : key_(arena), value_(arena), _cached_size_{0} {}

inline void PutRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PutRequest::~PutRequest() {
  // @@protoc_insertion_point(destructor:rocksdb.PutRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PutRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.key_.Destroy();
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData* PutRequest::GetClassData()
    const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassDataFull
      _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PutRequest, _impl_._cached_size_),
              false,
          },
          &PutRequest::MergeImpl,
          &PutRequest::kDescriptorMethods,
          &descriptor_table_rocksdb_5fservice_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<
    1, 2, 0, 35, 2>
    PutRequest::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            2, 8,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967292,  // skipmap
            offsetof(decltype(_table_), field_entries),
            2,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            &_PutRequest_default_instance_._instance,
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::rocksdb::PutRequest>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // string value = 2;
            {::_pbi::TcParser::FastUS1,
             {18, 63, 0, PROTOBUF_FIELD_OFFSET(PutRequest, _impl_.value_)}},
            // string key = 1;
            {::_pbi::TcParser::FastUS1,
             {10, 63, 0, PROTOBUF_FIELD_OFFSET(PutRequest, _impl_.key_)}},
        }},
        {{65535, 65535}},
        {{
            // string key = 1;
            {PROTOBUF_FIELD_OFFSET(PutRequest, _impl_.key_), 0, 0,
             (0 | ::_fl::kFcSingular | ::_fl::kUtf8String |
              ::_fl::kRepAString)},
            // string value = 2;
            {PROTOBUF_FIELD_OFFSET(PutRequest, _impl_.value_), 0, 0,
             (0 | ::_fl::kFcSingular | ::_fl::kUtf8String |
              ::_fl::kRepAString)},
        }},
        // no aux_entries
        {{"\22\3\5\0\0\0\0\0"
          "rocksdb.PutRequest"
          "key"
          "value"}},
};

PROTOBUF_NOINLINE void PutRequest::Clear() {
  // @@protoc_insertion_point(message_clear_start:rocksdb.PutRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* PutRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rocksdb.PutRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    const std::string& _s = this->_internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE,
        "rocksdb.PutRequest.key");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE,
        "rocksdb.PutRequest.value");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rocksdb.PutRequest)
  return target;
}

::size_t PutRequest::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:rocksdb.PutRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                          this->_internal_key());
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                          this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

void PutRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                           const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PutRequest*>(&to_msg);
  auto& from = static_cast<const PutRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rocksdb.PutRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PutRequest::CopyFrom(const PutRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:rocksdb.PutRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PutRequest::InternalSwap(PutRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_,
                                       arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_,
                                       arena);
}

::google::protobuf::Metadata PutRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PutResponse::_Internal {
 public:
};

PutResponse::PutResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rocksdb.PutResponse)
}
PutResponse::PutResponse(::google::protobuf::Arena* arena,
                         const PutResponse& from)
    : PutResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE PutResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
    : _cached_size_{0} {}

inline void PutResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
PutResponse::~PutResponse() {
  // @@protoc_insertion_point(destructor:rocksdb.PutResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PutResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData* PutResponse::GetClassData()
    const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassDataFull
      _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PutResponse, _impl_._cached_size_),
              false,
          },
          &PutResponse::MergeImpl,
          &PutResponse::kDescriptorMethods,
          &descriptor_table_rocksdb_5fservice_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
        PutResponse::_table_ = {
            {
                0,     // no _has_bits_
                0,     // no _extensions_
                1, 0,  // max_field_number, fast_idx_mask
                offsetof(decltype(_table_), field_lookup_table),
                4294967294,  // skipmap
                offsetof(decltype(_table_), field_entries),
                1,                                         // num_field_entries
                0,                                         // num_aux_entries
                offsetof(decltype(_table_), field_names),  // no aux_entries
                &_PutResponse_default_instance_._instance,
                nullptr,                            // post_loop_handler
                ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
                ::_pbi::TcParser::GetTable<
                    ::rocksdb::PutResponse>(),  // to_prefetch
#endif                                          // PROTOBUF_PREFETCH_PARSE_TABLE
            },
            {{
                // bool success = 1;
                {::_pbi::TcParser::SingularVarintNoZag1<
                     bool, offsetof(PutResponse, _impl_.success_), 63>(),
                 {8, 63, 0,
                  PROTOBUF_FIELD_OFFSET(PutResponse, _impl_.success_)}},
            }},
            {{65535, 65535}},
            {{
                // bool success = 1;
                {PROTOBUF_FIELD_OFFSET(PutResponse, _impl_.success_), 0, 0,
                 (0 | ::_fl::kFcSingular | ::_fl::kBool)},
            }},
            // no aux_entries
            {{}},
};

PROTOBUF_NOINLINE void PutResponse::Clear() {
  // @@protoc_insertion_point(message_clear_start:rocksdb.PutResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* PutResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rocksdb.PutResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rocksdb.PutResponse)
  return target;
}

::size_t PutResponse::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:rocksdb.PutResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

void PutResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PutResponse*>(&to_msg);
  auto& from = static_cast<const PutResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rocksdb.PutResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PutResponse::CopyFrom(const PutResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:rocksdb.PutResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PutResponse::InternalSwap(PutResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata PutResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rocksdb
namespace google {
namespace protobuf {}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type _static_init2_
    PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_rocksdb_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
