// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rocksdb_service.proto

#include "rocksdb_service.pb.h"
#include "rocksdb_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rocksdb {

static const char* RocksDBService_method_names[] = {
  "/rocksdb.RocksDBService/Put",
};

std::unique_ptr< RocksDBService::Stub> RocksDBService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RocksDBService::Stub> stub(new RocksDBService::Stub(channel, options));
  return stub;
}

RocksDBService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Put_(RocksDBService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RocksDBService::Stub::Put(::grpc::ClientContext* context, const ::rocksdb::PutRequest& request, ::rocksdb::PutResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rocksdb::PutRequest, ::rocksdb::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Put_, context, request, response);
}

void RocksDBService::Stub::async::Put(::grpc::ClientContext* context, const ::rocksdb::PutRequest* request, ::rocksdb::PutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rocksdb::PutRequest, ::rocksdb::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void RocksDBService::Stub::async::Put(::grpc::ClientContext* context, const ::rocksdb::PutRequest* request, ::rocksdb::PutResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rocksdb::PutResponse>* RocksDBService::Stub::PrepareAsyncPutRaw(::grpc::ClientContext* context, const ::rocksdb::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rocksdb::PutResponse, ::rocksdb::PutRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Put_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rocksdb::PutResponse>* RocksDBService::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::rocksdb::PutRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPutRaw(context, request, cq);
  result->StartCall();
  return result;
}

RocksDBService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RocksDBService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RocksDBService::Service, ::rocksdb::PutRequest, ::rocksdb::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RocksDBService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rocksdb::PutRequest* req,
             ::rocksdb::PutResponse* resp) {
               return service->Put(ctx, req, resp);
             }, this)));
}

RocksDBService::Service::~Service() {
}

::grpc::Status RocksDBService::Service::Put(::grpc::ServerContext* context, const ::rocksdb::PutRequest* request, ::rocksdb::PutResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rocksdb

